import CountriesItem, {
  CountriesItemProps,
} from "@/components/countries-item/countries-item";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "Countries",
    description: "Generated by create next app",
  };
const Countries = async () => {
  const res = await fetch("https://www.sarirniroo.ir/Mobile/countries");
  const data = await res.json();
  return (
    <div className="">
      <div className="w-[90%] mx-auto">
        <h1 className="text-3xl hidden lg:block font-bold text-center my-8 text-black">
          Books from ...
        </h1>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-7 gap-4">
          {data.map((item: CountriesItemProps) => {
            return (
              <CountriesItem
                key={item.flag_url}
                flag_url={item.flag_url}
                name={item.name}
                iso_code={item.iso_code}
              />
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default Countries;
