import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/layout/layout";
import {AppContextProvider} from "@/app-context/app-context";



export const metadata: Metadata = {
  title: {
    default:"Soul Shelf",
    template:'Soul Shelf | %s'
  },
  icons: {
    icon: [
      {
        url: "./soul-shelf1.svg",
        type: "image/png",
      },
    ],
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
      <Layout>
        {children}
        </Layout>
      </AppContextProvider>
      </body>
    </html>
  );
}
